### ISSUE TITLE
BulkInsert fails with error cannot insert because column ID cannot accept null

### ISSUE THREAD

**Issue by chinarosesz** [tiagoln/BulkExtensions#7]
Sorry I'm in a hurry and don't have a lot of repo steps right now, but when I get a chance, I'll update this thread to include more details. Just wanted to let you know that I tried the latest version today and had to go back to 1.2.2 in order for the insertion to work. 

Will update with details soon...

**Comment by tiagoln** [comment]
Thanks for the heads up. I think I found the problem, tomorrow I'll test the solution and release an update with the fix.

**Comment by tiagoln** [comment]
One question tho, do you have any foreign key in the entity you are trying to bulk insert?

**Comment by chinarosesz** [comment]
Nope, just a primary key in the table.

**Comment by tiagoln** [comment]
It was on plain BulkInsert(collection); method or with InsertOptions.OutputIdentity?

**Comment by chinarosesz** [comment]
Plain BulkInsert(collection). I actually haven't used OutputIdentity option before since I haven't found a need for it yet. Basically as soon I updated to the new version this morning, I started seeing the insertion failing, switched back to the previous version, things went back to normal.

**Comment by tiagoln** [comment]
I released a new update, I think it solves this problem. Please give it a try when you can.

**Comment by chinarosesz** [comment]
Still showing up errors when calling insert or update.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'ID', table 'SomeDatabase.dbo.SomeTable'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at EntityFramework.BulkExtensions.Commons.Context.DbContextWrapper.ExecuteSqlCommand(String command)
   at EntityFramework.BulkExtensions.Commons.BulkOperations.BulkInsertOrUpdate.EntityFramework.BulkExtensions.Commons.BulkOperations.IBulkOperation.CommitTransaction[TEntity](IDbContextWrapper context, IEnumerable`1 collection, BulkOptions options)
   at EntityFramework.BulkExtensions.BulkExtensions.BulkInsertOrUpdate[TEntity](DbContext context, IEnumerable`1 entities, InsertOptions options)
   
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at VsoReleaseDefinitionPump.Program.Main(String[] args) in D:\dev\Program.cs:line 11
Press any key to continue . . .

**Comment by InntecDeveloper** [comment]
I am also getting this error except with the "BulkInsertOrUpdate" function.  I do have foreign keys in the entities I am trying to insert/update.  Let me know if there is any more data I can provide.

### Exception Details
**Message**
Cannot insert the value NULL into column 'PlayerId', table 'Zelus.db_owner.PlayerCharacters'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
**Stack Trace**
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at EntityFramework.BulkExtensions.Commons.Context.DbContextWrapper.ExecuteSqlCommand(String command)
   at EntityFramework.BulkExtensions.Commons.BulkOperations.BulkInsertOrUpdate.EntityFramework.BulkExtensions.Commons.BulkOperations.IBulkOperation.CommitTransaction[TEntity](IDbContextWrapper context, IEnumerable`1 collection, BulkOptions options)
   at EntityFramework.BulkExtensions.BulkExtensions.BulkInsertOrUpdate[TEntity](DbContext context, IEnumerable`1 entities, InsertOptions options)
   at Zelus.Web.Models.Synchronization.PlayerCharacterSynchronizer.Execute(Int32 guildId) in c:\Users\ryanw\documents\visual studio 2017\Projects\Zelus\Zelus.Web\Models\Synchronization\PlayerCharacterSynchronizer.cs:line 40

**Comment by tiagoln** [comment]
I've been digging the problem looking at the stack trace sent by InntecDeveloper, and it happens because the table you are trying to insert data has a foreign key NOT NULL constraint, the SqlBulkCopy with default options circumvents all constraints, but can leave your table with invalid data. 

This scenario is used in the plain BulkInsert method to insert directly to your table, but when you use the 'OutputIdentity' option or any other method(BulkUpdate, etc), the library bulk inserts the data into a temporary table (Using SqlBulkCopy, without checking constraints, as previously mentioned) and then 'MERGE' it with your table. The 'MERGE' command checks constraints, therefore, it will raise an exception in case any constraint are violated, in this case the column 'PlayerId' doesn't have a valid foreign key value as it is trying to insert a NULL value in a NOT NULL column. 

So, in fact, the actual problem is that you have to make sure the data you are trying to insert complains with the constraints, or perhaps make your 'PlayerId' nullable if you want null values. In the stack trace posted by chinarosesz the method used is also BulkInsertOrUpdate and the exception is also the same.

I've teste some scenarios here and ended up with the same error when the constraints were not respected, but when I altered the entities property values in the collection to make it comply with the constraints the operations executed without issues, so I think it is best to keep this behavior to prevent corrupted or invalid data to be inserted in the database. What do you think?

**Comment by InntecDeveloper** [comment]
The first thing I did when I saw the above error was ensure that all entities had valid PlayerIds.  The model I am using has a non-nullable int for PlayerId:

~~~~
public partial class PlayerCharacter
    {
        public int PlayerId { get; set; }
        public int CharacterId { get; set; }
        public int GearLevel { get; set; }
        public int StarLevel { get; set; }
        public int CharacterLevel { get; set; }
        public int NumberOfZetas { get; set; }
        public string CharacterUrl { get; set; }
        public virtual Character Character { get; set; }
        public virtual Player Player { get; set; }
    }
~~~~

I also validated that all of the IDs matched with their references.  In this case, the PlayerIds range from 1 to 49.  When I ran this query on the list:

~~~~
var test = playerCharacters.Where(pc => pc.PlayerId > 49 || pc.PlayerId == 0).ToList();
_db.BulkInsertOrUpdate(playerCharacters);
~~~~

The test variable returns 0 rows.  I was concerned that maybe the virtual Player/Characters were throwing it off, so I made sure those were correctly populated as well.  Maybe I need to remove those from my model?

As for your question:  I think it does make sense for you to keep the constraints.  Most of the time the operation would fail (from sql) if it didnt meet those constraints.

**Comment by tiagoln** [comment]
All bulk operation in the library ignores the virtual properties so I think that's not the case. I noticed that there are no primary keys on this class, does any of  the foreign keys also act as primary key, or perhaps both combined? If so this may be the problem. If you add a property to be exclusively the primary key it should work, you can leave everything as it is and just add a key property. I had some problems with entities that do not have a primary key and instead use the foreign keys as primary keys, this is something that I'm trying to figure out how to handle yet.

**Comment by InntecDeveloper** [comment]
Yes, I was using a composite key comprised of the PlayerId and the CharacterId.  I have since added a single primary key and it is working beautifully.  Thank you for the help!

**Comment by tiagoln** [comment]
Nice!!! I'll build some test cases with composite keys, right now my library doesn't play well with them, but I have some ideas that I think will work. If everything work out as planned I should have a new update this week to fix this problem. I also found out that Ids that are not database generated have a problem as well, it seems to be related with the composite keys stuff.

**Comment by chinarosesz** [comment]
OMG, I must have been smoking something. I can't believe I was still referencing the previous version when I got that error. I thought I already updated to the new version, but apparently not. Trying to meet some deadline and your mind is just ^-^ lol..

**Comment by tiagoln** [comment]
😂 No problem! One question, is this 'ID' column database generated? Because if it isn't, it'll have the same problem as the composite keys. I'll try to fix this issues as soon as possible.

**Comment by InntecDeveloper** [comment]
@tiagoln If you were asking me, then yes the Id column I put in place for the primary key is database generated.  When I was using a composite key, they were not, because each column was a foreign key to a different table.

**Comment by tiagoln** [comment]
I was asking chinarosesz, but thanks anyway. I made some changes today and managed to make the library work properly with composite keys, it should work with your scenario. I tested with EF6 and now I'm going to test with EFCore, if everything works fine I'll release an update to the nuget packages today. This update also improves the performance of the InsertOrUpdate when using collections with many items, like +100,000.

**Comment by chinarosesz** [comment]
The ID column isn't generated. For now, I'm using insert and update separately and it works with the latest version.

**Comment by tiagoln** [comment]
I've released a new nuget package that should fix the problems with composite keys that InntecDeveloper had and the key columns that do not have generated values chinarosesz reported. When you have some time, please check if it solves those issues.

**Comment by tiagoln** [comment]
This new version also boosts performance, I tweaked the code that transforms the entities collection to DbDataReader(used by the SqlBulkCopy to insert the data). It should scale better for big collections(+100.000), and when using the OuputIdentity option.

**Comment by InntecDeveloper** [comment]
Awesome!  Thank you for the support.  I will probably be able to test the composite key fixes either Thursday or Friday, and I will let you know.

**Comment by tiagoln** [comment]
Thanks for the update :D
